services:
  - type: web
    name: action-collector
    env: node
    buildCommand: "cd server && npm install"
    startCommand: "cd server && npm start"
    plan: free
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
