const { getTransporter } = require('../config/email');

const sendEmail = async (req, res) => {
  try {
    const transporter = getTransporter();
    
    if (!transporter) {
      return res.status(503).json({ 
        error: 'Email service not configured. Please set EMAIL_USER and EMAIL_PASS in .env file with Gmail App Password.' 
      });
    }

    const { recipients, subject, summary } = req.body;

    if (!recipients || !summary) {
      return res.status(400).json({ error: 'Recipients and summary are required' });
    }

    const mailOptions = {
      from: `"Meeting Summarizer" <${process.env.EMAIL_USER}>`,
      to: recipients.join(', '),
      subject: subject || 'Meeting Summary',
      html: `
        <h2>Meeting Summary</h2>
        <div style="white-space: pre-wrap; font-family: Arial, sans-serif; line-height: 1.6;">
          ${summary.replace(/\n/g, '<br>')}
        </div>
        <br>
        <p><em>Generated by Meeting Notes Summarizer</em></p>
      `
    };

    await transporter.sendMail(mailOptions);
    res.json({ message: 'Email sent successfully' });
  } catch (error) {
    console.error('Error sending email:', error);
    res.status(500).json({ error: 'Failed to send email' });
  }
};

module.exports = {
  sendEmail
};
